### ISSUE TITLE
AWS ACL Error after following setup docs

### ISSUE THREAD

**Issue by geraldinefiser** [ryanto/next-s3-upload#64]
Hi,
I followed the setup instructions but I am getting an error on upload: "AccessControlListNotSupported: The bucket does not allow ACLs" along with a 400 on PUT.

I copied the bucket settings and created the IAM new policy as the docs said.
<img width="543" alt="Screen Shot 2022-04-04 at 3 30 00 PM" src="https://user-images.githubusercontent.com/6376789/161618327-20dbbd99-907c-4874-a9fd-6d30ae4bfa44.png">

**Comment by ryanto** [comment]
Thanks for reporting this!

It looks like AWS changed the default permissions to block ACLs on new buckets. Right now this library uses an ACL rule to make uploads public, since most folks using this library are uploading web items like images.

You can enable ACLs under the Permissions -> Object ownership section of your S3 bucket.

<img width="1569" alt="Screen Shot 2022-04-05 at 11 22 50 AM" src="https://user-images.githubusercontent.com/89411/161788676-242b5aa8-ce91-4356-955e-90d28dae961d.png">
 

That said, I think I can update this library to not use ACLs. I'll update here once I get more info :)

**Comment by geraldinefiser** [comment]
Thanks! Sounds good, I made the change for now to allow ACL and it is working. 👍

**Comment by ryanto** [comment]
Awesome, glad to hear the change got it working for you.

I just updated this library to no longer use ACLs. 

If you upgrade to version `0.2.0` you can follow the new setup instructions here that show you how to add a bucket policy: https://next-s3-upload.codingvalue.com/setup#bucket-permissions
