### ISSUE TITLE
When hitting the API route directly - showing sensitive data? 

### ISSUE THREAD

**Issue by michaelsoriano** [ryanto/next-s3-upload#90]
This is more of a question, but when I hit the api route directly, it seems to show api keys etc? It doesnt look like its the secret key for the IAM account, and seems to change on every reload. Can you tell me what these are? Should I be concerned about exposing this data? 

![next-s3-upload-screenshot](https://user-images.githubusercontent.com/5881081/186304513-8ab933d2-1a83-4725-87f3-3871a1a5dc88.PNG)

Thanks.

**Comment by ryanto** [comment]
Hi there, great question!

What you're seeing is a set of temporary access keys given to the browser so that it can upload the file to S3. 

Here's how the whole process works:

When the browser wants to upload a file to S3 it first makes a request to the backend asking for permission. The backend then generates a set of temporary IAM credentials on the server that only gives access for uploading a specific file to a predetermined location in your S3 bucket.

The temporary credentials and policy are then given the to browser and the browser executes them to upload to S3. If the browser tries do to any other operation it will fail. The temporary browser credentials expire after one hour.

Hopefully that helps answer your question, but let me know if it doesn't!

**Comment by michaelsoriano** [comment]
Yes that makes sense. Nothing to worry about I suppose. Thank you for answering.
